camera:
  brightness: 31
  contrast: 91
  saturation: 118
  exposure: 0
  gain: 0
hsv:
  lower:
    h: 29
    s: 49
    v: 241
  upper:
    h: 30
    s: 255
    v: 244
morphology:
  erode_iterations: 2
  dilate_iterations: 0
  kernel_size: 5
detection:
  min_contour_area: 500
